### PR TITLE
Upgrade dependencies to latest

### PR DESCRIPTION
**Pull request by jeaye**
This was done using: lein ancient upgrade :check-clojure :all

All tests/specs pass locally.

### CODE REVIEW

**Comment by aprobus** [comment]
Thanks @jeaye !

**Comment by jeaye** [comment]
Thank you! I'm currently waiting for a [bug fix in byte-streams](https://github.com/ztellman/byte-streams/pull/27) to be merged. At which point, I'd like to send you another PR so we can help propagate the version update up the tree.

**Comment by jeaye** [comment]
@aprobus Looks like that byte-streams bit isn't going to be merged. Will you deploy a new version now?

There are a couple of other changes that could be made to JWT: the uberjar profile should, ideally, use `:aot :all` and the dev profile should, ideally, use `*warn-on-reflection* true`. After the latter is enabled, you'll find that there are several reflection warnings, which can be addressed with type hints.

It's important to address these, since that reflection is terribly slow. Here's an example of what I'm seeing:

```text
Reflection warning, jerks_whistling_tunes/utils.clj:9:3 - call to method decode can't be resolved (target class is unknown).
Reflection warning, jerks_whistling_tunes/utils.clj:14:12 - call to method encode can't be resolved (target class is unknown).
Reflection warning, jerks_whistling_tunes/utils.clj:14:3 - call to java.lang.String ctor can't be resolved.
Reflection warning, jerks_whistling_tunes/core.clj:20:5 - call to method getBytes can't be resolved (target class is unknown).
Reflection warning, jerks_whistling_tunes/core.clj:29:7 - call to java.lang.String ctor can't be resolved.
Reflection warning, jerks_whistling_tunes/core.clj:64:22 - reference to field alg can't be resolved.
Reflection warning, jerks_whistling_tunes/core.clj:67:19 - call to method sign can't be resolved (target class is unknown).
Reflection warning, jerks_whistling_tunes/core.clj:110:23 - reference to field alg can't be resolved.
Reflection warning, jerks_whistling_tunes/core.clj:127:9 - call to method valid_signature_QMARK_ on java.lang.Object can't be resolved (no such method).
Reflection warning, jerks_whistling_tunes/sign.clj:24:16 - call to method update on java.security.Signature can't be resolved (argument types: unknown).
Reflection warning, jerks_whistling_tunes/sign.clj:35:16 - call to method initVerify on java.security.Signature can't be resolved (argument types: unknown).
Reflection warning, jerks_whistling_tunes/sign.clj:35:16 - call to method update on java.security.Signature can't be resolved (argument types: unknown).
Reflection warning, jerks_whistling_tunes/sign.clj:58:19 - call to method update on javax.crypto.Mac can't be resolved (argument types: unknown).
Reflection warning, jerks_whistling_tunes/sign.clj:106:37 - reference to field getPublic can't be resolved.
Reflection warning, jerks_whistling_tunes/sign.clj:106:54 - reference to field getPrivate can't be resolved.
```

Is this something you'd be willing to fix?

**Comment by aprobus** [comment]
@jeaye `0.3.0` should be out now. Sorry it took so long! It's been a while since I released anything to clojars and gpg was causing problems. It shouldn't be too difficult to get rid of the reflection, but I probably won't be able to get around to it for a bit.

**Comment by jeaye** [comment]
Thank you! I think I can get to the reflection this weekend, if you don't. I did get that byte-streams bug fixed, but haven't been able to squeeze a release out of him yet. Once that happens, I'll give you another PR with the update.

Cheers.

**Pull request merged**
